version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      - 'MYSQL_DATABASE=messaging'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '33066:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: