version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - 'MYSQL_DATABASE=messaging'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '33066:3306'
    volumes:
      - dbdata:/var/lib/mysql
  flyway-migration:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -user=root -password=verysecret -defaultSchema=messaging migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql

volumes:
  dbdata: